source $HOME/.config/nvim/plugins.vim
source $HOME/.config/nvim/defaults.vim
source $HOME/.config/nvim/misc.vim
source $HOME/.config/nvim/NERDTree.vim
source $HOME/.config/nvim/airline.vim
source $HOME/.config/nvim/barbar.vim
source $HOME/.config/nvim/lsp.vim
source $HOME/.config/nvim/telescope.vim
source $HOME/.config/nvim/theme.vim
source $HOME/.config/nvim/remaps.vim
